import type { Point2, SectionRegion } from './drawing-types'

/**
 * Section hatching.
 *
 * Hatching is what tells a reader which parts of a section view are solid
 * material and which are holes they are looking through. Getting it wrong — a
 * bore filled in, a web left blank — misreads the part in a way no dimension
 * can correct, so the fill has to follow the real cut boundary rather than a
 * bounding box.
 *
 * Lines are generated by scanning across the region and clipping each one
 * against every boundary, holes included. Crossings are paired by the even-odd
 * rule, which is the same rule that decides material from hole everywhere else
 * in this application.
 */

/** Ignore hatch fragments shorter than this; they read as dirt on the print. */
const MINIMUM_SEGMENT = 1e-6

function crossingsAlongLine(
  polygons: Point2[][],
  offset: number,
  direction: Point2,
  normal: Point2,
): number[] {
  const crossings: number[] = []
  for (const polygon of polygons) {
    for (let index = 0; index < polygon.length; index += 1) {
      const a = polygon[index]
      const b = polygon[(index + 1) % polygon.length]
      const da = a[0] * normal[0] + a[1] * normal[1] - offset
      const db = b[0] * normal[0] + b[1] * normal[1] - offset

      // Treating zero as "not below" counts a vertex sitting exactly on the
      // scan line once rather than twice, which is what keeps the even-odd
      // pairing from inverting for the rest of that line.
      if (da < 0 === db < 0) continue

      const t = da / (da - db)
      const point: Point2 = [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t]
      crossings.push(point[0] * direction[0] + point[1] * direction[1])
    }
  }
  return crossings.sort((first, second) => first - second)
}

/**
 * Hatch every region on one shared grid of scan lines.
 *
 * The grid is global but the pairing is per region, so two separate pieces of
 * material in the same section are filled with lines that continue across the
 * gap — as a single cut through one part should look — without material being
 * drawn in the space between them.
 */
export function hatchRegions(
  regions: SectionRegion[],
  spacing: number,
  angleRadians = Math.PI / 4,
): [Point2, Point2][] {
  if (spacing <= 0) return []

  const direction: Point2 = [Math.cos(angleRadians), Math.sin(angleRadians)]
  const normal: Point2 = [-Math.sin(angleRadians), Math.cos(angleRadians)]

  const allPoints = regions.flatMap((region) => [region.outer, ...region.holes]).flat()
  if (allPoints.length < 3) return []

  const offsets = allPoints.map((point) => point[0] * normal[0] + point[1] * normal[1])
  const first = Math.ceil(Math.min(...offsets) / spacing) * spacing
  const last = Math.max(...offsets)

  const segments: [Point2, Point2][] = []
  for (let offset = first; offset <= last; offset += spacing) {
    for (const region of regions) {
      const crossings = crossingsAlongLine([region.outer, ...region.holes], offset, direction, normal)
      for (let index = 0; index + 1 < crossings.length; index += 2) {
        const from = crossings[index]
        const to = crossings[index + 1]
        if (to - from <= MINIMUM_SEGMENT) continue
        segments.push([
          [direction[0] * from + normal[0] * offset, direction[1] * from + normal[1] * offset],
          [direction[0] * to + normal[0] * offset, direction[1] * to + normal[1] * offset],
        ])
      }
    }
  }
  return segments
}
